// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/about/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/about/content.get').default>>>>
    }
    '/api/about/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/about/list.get').default>>>>
    }
    '/api/about/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/about/upload.post').default>>>>
    }
    '/api/articles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/articles/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/articles/[id].get').default>>>>
    }
    '/api/articles/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/articles/import.post').default>>>>
    }
    '/api/articles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/articles/index.get').default>>>>
    }
    '/api/gallery/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gallery/add.post').default>>>>
    }
    '/api/gallery/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gallery/delete.post').default>>>>
    }
    '/api/gallery/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gallery/list.get').default>>>>
    }
    '/api/gallery/local': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gallery/local.get').default>>>>
    }
    '/api/proxy/image': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proxy/image').default>>>>
    }
    '/api/videos': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos').default>>>>
    }
    '/api/videos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/[id].delete').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/[id]').default>>>>
    }
    '/api/xpc/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/xpc/import.post').default>>>>
    }
    '/api/xpc/preview': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/xpc/preview').default>>>>
    }
    '/api/xpc/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/xpc/test').default>>>>
    }
    '/api/xpc/works': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/xpc/works').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}