// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/15 15:12:12
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/lenovo/CodeRep/mrwz-wang/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/components/icons/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/plugins/**/*.{js,ts,mjs}","C:/Users/lenovo/CodeRep/mrwz-wang/composables/**/*.{js,ts,mjs}","C:/Users/lenovo/CodeRep/mrwz-wang/utils/**/*.{js,ts,mjs}","C:/Users/lenovo/CodeRep/mrwz-wang/pages/about/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/about.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/api-test.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/articles.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/gallery.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/import-xpc.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/photos.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/admin/videos.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/articles/[id].vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/articles/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/photos/[id].vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/photos/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/videos/[id].vue","C:/Users/lenovo/CodeRep/mrwz-wang/pages/videos/index.vue","C:/Users/lenovo/CodeRep/mrwz-wang/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lenovo/CodeRep/mrwz-wang/app.config.{js,ts,mjs}","C:/Users/lenovo/CodeRep/mrwz-wang/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;